packages:
  - "."
  - "packages/*"

allowBuilds:
  bufferutil: false
  esbuild: true
  happy: false
  keccak: false
  utf-8-validate: false

patchedDependencies:
  happy@1.2.0: patches/happy@1.2.0.patch
